name: ready-review-pr
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ "main" ]

jobs:
  ready-review-PR-main-job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Run ready-review-pr
        run: | 
          echo "Running only on ready-to-review PR"
          echo "${{ github.event_name }}"
          echo "${{ github.event.action }}"
