name: test1
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test1-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run test1-job1-echo
        run: | 
          echo "Running test1-job1"
          echo "${{ github.event_name }}"
          echo "${{ github.event.action }}"
